# Generated by Django 2.2.13 on 2021-01-31 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('profession', models.CharField(choices=[('Writer', 'Writer'), ('Programmer', 'Programmer'), ('Biologist', 'Biologist'), ('Mathematician', 'Mathematician'), ('Other', 'Other')], default='Writer', help_text='Type of Employee', max_length=124)),
                ('ranking', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')], help_text='Employees are ranked from level 1-5 according to their expertise.', max_length=128)),
                ('rating', models.CharField(choices=[('Probation', 'Probation'), ('Beginner', 'Beginner'), ('Under Investigation', 'Under Investigation'), ('Novice', 'Novice'), ('Expert', 'Expert')], help_text="Status of the employee's account", max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
