# Generated by Django 3.1.5 on 2021-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(help_text='Number of words, e.g: 300', max_length=32)),
                ('level', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University'), ('Masters', 'Masters'), ('PHD', 'PHD')], default='College', max_length=32)),
                ('language', models.CharField(choices=[('English UK', 'English UK'), ('English US', 'English US'), ('English CA', 'English CA'), ('English AU', 'English AU'), ('Other', 'Other')], default='English US', max_length=32)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(default='', help_text='Topic of the assignment', max_length=256)),
                ('subject', models.CharField(default='', help_text='Subject, e.g: Computer Science, Nursing', max_length=128)),
                ('sources', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('8+', '8+')], default='1', max_length=16)),
                ('style', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Havard', 'Havard'), ('Chicago', 'Chicago'), ('Turbia', 'Turbian'), ('Other', 'Other')], default='APA', max_length=64)),
                ('description', models.TextField(default='', help_text='Assignment Descritption')),
                ('uploads', models.FileField(default='', help_text='File uploads for the assignment', upload_to='')),
                ('price', models.IntegerField(default='2.50', help_text='Total payment of the assignment')),
            ],
        ),
    ]
