# Generated by Django 3.1.5 on 2021-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Precise deadline of the assignment', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='language',
            field=models.CharField(choices=[('English UK', 'English UK'), ('English US', 'English US'), ('English CA', 'English CA'), ('English AU', 'English AU'), ('Other', 'Other')], default='English US', help_text='Preferred English version of the client', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University'), ('Masters', 'Masters'), ('PHD', 'PHD')], default='College', help_text='The educational level of the paper', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='sources',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('8+', '8+')], default='1', help_text="Amount of sources needed by the client. Put 'Other' if exceeds eight.", max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='style',
            field=models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Havard', 'Havard'), ('Chicago', 'Chicago'), ('Turbia', 'Turbian'), ('Other', 'Other')], default='APA', help_text='Preferred formatting style by the client.', max_length=64),
        ),
    ]
