# Generated by Django 2.2.13 on 2021-02-01 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='order_assigned',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_assigned', to='mainapp.Order'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='writer_assigned',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_topic', to=settings.AUTH_USER_MODEL),
        ),
    ]
