# Generated by Django 3.1.5 on 2021-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210121_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uploads',
            field=models.FileField(blank=True, default='', help_text='File uploads for the assignment', null=True, upload_to='uploads/'),
        ),
    ]
