# Generated by Django 3.1.5 on 2021-01-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210127_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_selected',
            new_name='bid_order',
        ),
    ]
