# Generated by Django 3.1.5 on 2021-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210128_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_order',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_order',
            field=models.ManyToManyField(blank=True, to='mainapp.Order'),
        ),
    ]
