# Generated by Django 3.1.5 on 2021-01-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210128_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_order',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.order'),
        ),
    ]
