# Generated by Django 3.1.5 on 2021-01-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210128_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user_bid',
            new_name='bid_placed_by',
        ),
    ]
