# Generated by Django 3.1.5 on 2021-01-28 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0012_auto_20210128_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_placed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='writer',
        ),
        migrations.AddField(
            model_name='order',
            name='bid_placed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
